services:
  backend-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "453:453"

  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
